// Product Models with their configurations
export const PRODUCT_MODELS = [
  {
    value: "TP LD-51 Battery with Solax- Fronus Inverter",
    label: "TP LD-51 Battery with Solax- Fronus Inverter",
    reward: 2000,
    requiresInverter: true,
    isBattery: true,
  },
  {
    value: "Fronus 5.12kW Battery with Solax- Fronus Inverter",
    label: "Fronus 5.12kW Battery with Solax- Fronus Inverter",
    reward: 2000,
    requiresInverter: true,
    isBattery: true,
  },
  {
    value: "TP LD-51 Battery",
    label: "TP LD-51 Battery",
    reward: 1500,
    requiresInverter: false,
    isBattery: true,
  },
  {
    value: "Fronus 5.12kW Battery",
    label: "Fronus 5.12kW Battery",
    reward: 1500,
    requiresInverter: false,
    isBattery: true,
  },
  {
    value: "4.2kW - PV 5200",
    label: "4.2kW - PV 5200",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "6.2kW - PV 7200",
    label: "6.2kW - PV 7200",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "8kW - PV 9200",
    label: "8kW - PV 9200",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "10kW - PV 12200",
    label: "10kW - PV 12200",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "6KW - X1 Genki",
    label: "6KW - X1 Genki",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "8kW - X1 Genki",
    label: "8kW - X1 Genki",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "10kW - X1 Genki",
    label: "10kW - X1 Genki",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "12kW - X1 Genki",
    label: "12kW - X1 Genki",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "10kW - X3 Genki",
    label: "10kW - X3 Genki",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "15kW - X3 Genki",
    label: "15kW - X3 Genki",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "5KW - X3 Mic G2",
    label: "5KW - X3 Mic G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "10KW - X3 Mic G2",
    label: "10KW - X3 Mic G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "15KW - X3 Mic G2",
    label: "15KW - X3 Mic G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "20KW - X3 Pro G2",
    label: "20KW - X3 Pro G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "25KW - X3 Pro G2",
    label: "25KW - X3 Pro G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "30KW - X3 Pro G2",
    label: "30KW - X3 Pro G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "40KW - X3 Mega G2",
    label: "40KW - X3 Mega G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "50KW - X3 Mega G2",
    label: "50KW - X3 Mega G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "60KW - X3 Mega G2",
    label: "60KW - X3 Mega G2",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "80KW - X3 Forth",
    label: "80KW - X3 Forth",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "100KW - X3 Forth",
    label: "100KW - X3 Forth",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "110KW - X3 Forth",
    label: "110KW - X3 Forth",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
  {
    value: "125KW - X3 Forth",
    label: "125KW - X3 Forth",
    reward: 1500,
    requiresInverter: false,
    isBattery: false,
  },
];

// Serial number statuses
export const SERIAL_STATUSES = [
  { value: "ACTIVE", label: "Active" },
  { value: "VERIFIED", label: "Verified" },
  { value: "PENDING", label: "Pending Verification" },
  { value: "REGISTERED", label: "Registered" },
];

export const PAYMENT_METHOD = [
  { value: "UBANK", label: "UBANK" },
  { value: "UPaisa", label: "UPaisa" },
  { value: "NayaPay", label: "NayaPay" },
];

export const PROVINCES = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Gilgit Baltistan",
  "Azad Kashmir",
  "Islamabad",
] as const;

export type Province = (typeof PROVINCES)[number];

// City to province mapping
export const CITY_TO_PROVINCE: Record<string, Province> = {
  // Federal Capital
  Islamabad: "Islamabad",

  // Punjab Cities
  "Ahmed Nager Chatha": "Punjab",
  "Ahmadpur East": "Punjab",
  "Ali Khan Abad": "Punjab",
  Alipur: "Punjab",
  Arifwala: "Punjab",
  Attock: "Punjab",
  Bhera: "Punjab",
  Bhalwal: "Punjab",
  Bahawalnagar: "Punjab",
  Bahawalpur: "Punjab",
  Bhakkar: "Punjab",
  Burewala: "Punjab",
  Chillianwala: "Punjab",
  Chakwal: "Punjab",
  Chichawatni: "Punjab",
  Chiniot: "Punjab",
  Chishtian: "Punjab",
  Daska: "Punjab",
  "Darya Khan": "Punjab",
  "Dera Ghazi Khan": "Punjab",
  Dhaular: "Punjab",
  Dina: "Punjab",
  Dinga: "Punjab",
  Dipalpur: "Punjab",
  Faisalabad: "Punjab",
  Ferozewala: "Punjab",
  "Fateh Jang": "Punjab",
  "Ghakhar Mandi": "Punjab",
  Gojra: "Punjab",
  Gujranwala: "Punjab",
  Gujrat: "Punjab",
  "Gujar Khan": "Punjab",
  Hafizabad: "Punjab",
  Haroonabad: "Punjab",
  Hasilpur: "Punjab",
  "Haveli Lakha": "Punjab",
  Jatoi: "Punjab",
  Jalalpur: "Punjab",
  Jattan: "Punjab",
  Jampur: "Punjab",
  Jaranwala: "Punjab",
  Jhang: "Punjab",
  Jhelum: "Punjab",
  Kalabagh: "Punjab",
  "Karor Lal Esan": "Punjab",
  Kasur: "Punjab",
  Kamalia: "Punjab",
  Kamoke: "Punjab",
  Khanewal: "Punjab",
  Khanpur: "Punjab",
  Kharian: "Punjab",
  Khushab: "Punjab",
  "Kot Addu": "Punjab",
  Jauharabad: "Punjab",
  Lahore: "Punjab",
  Lalamusa: "Punjab",
  Layyah: "Punjab",
  "Liaquat Pur": "Punjab",
  Lodhran: "Punjab",
  Malakwal: "Punjab",
  Mamoori: "Punjab",
  Mailsi: "Punjab",
  "Mandi Bahauddin": "Punjab",
  "Mian Channu": "Punjab",
  Mianwali: "Punjab",
  Multan: "Punjab",
  Murree: "Punjab",
  Muridke: "Punjab",
  "Mianwali Bangla": "Punjab",
  Muzaffargarh: "Punjab",
  Narowal: "Punjab",
  "Nankana Sahib": "Punjab",
  Okara: "Punjab",
  "Renala Khurd": "Punjab",
  Pakpattan: "Punjab",
  Pattoki: "Punjab",
  "Pir Mahal": "Punjab",
  Qaimpur: "Punjab",
  "Qila Didar Singh": "Punjab",
  Rabwah: "Punjab",
  Raiwind: "Punjab",
  Rajanpur: "Punjab",
  "Rahim Yar Khan": "Punjab",
  Rawalpindi: "Punjab",
  Sadiqabad: "Punjab",
  Safdarabad: "Punjab",
  Sahiwal: "Punjab",
  "Sangla Hill": "Punjab",
  "Sarai Alamgir": "Punjab",
  Sargodha: "Punjab",
  Shakargarh: "Punjab",
  Sheikhupura: "Punjab",
  Sialkot: "Punjab",
  Sohawa: "Punjab",
  Soianwala: "Punjab",
  Siranwali: "Punjab",
  Talagang: "Punjab",
  Taxila: "Punjab",
  "Toba Tek Singh": "Punjab",
  Vehari: "Punjab",
  "Wah Cantonment": "Punjab",
  Wazirabad: "Punjab",

  // Sindh Cities
  Badin: "Sindh",
  Bhirkan: "Sindh",
  "Rajo Khanani": "Sindh",
  Chak: "Sindh",
  Dadu: "Sindh",
  Digri: "Sindh",
  Diplo: "Sindh",
  Dokri: "Sindh",
  Ghotki: "Sindh",
  Haala: "Sindh",
  Hyderabad: "Sindh",
  Islamkot: "Sindh",
  Jacobabad: "Sindh",
  Jamshoro: "Sindh",
  Jungshahi: "Sindh",
  Kandhkot: "Sindh",
  Kandiaro: "Sindh",
  Karachi: "Sindh",
  Kashmore: "Sindh",
  "Keti Bandar": "Sindh",
  Khairpur: "Sindh",
  Kotri: "Sindh",
  Larkana: "Sindh",
  Matiari: "Sindh",
  Mehar: "Sindh",
  "Mirpur Khas": "Sindh",
  Mithani: "Sindh",
  Mithi: "Sindh",
  Mehrabpur: "Sindh",
  Moro: "Sindh",
  Nagarparkar: "Sindh",
  Naudero: "Sindh",
  "Naushahro Feroze": "Sindh",
  Naushara: "Sindh",
  Nawabshah: "Sindh",
  Nazimabad: "Sindh",
  Qambar: "Sindh",
  Qasimabad: "Sindh",
  Ranipur: "Sindh",
  Ratodero: "Sindh",
  Rohri: "Sindh",
  Sakrand: "Sindh",
  Sanghar: "Sindh",
  Shahbandar: "Sindh",
  Shahdadkot: "Sindh",
  Shahdadpur: "Sindh",
  "Shahpur Chakar": "Sindh",
  Shikarpaur: "Sindh",
  Sukkur: "Sindh",
  Tangwani: "Sindh",
  "Tando Adam Khan": "Sindh",
  "Tando Allahyar": "Sindh",
  "Tando Muhammad Khan": "Sindh",
  Thatta: "Sindh",
  Umerkot: "Sindh",
  Warah: "Sindh",

  // Khyber Pakhtunkhwa Cities
  Abbottabad: "Khyber Pakhtunkhwa",
  Adezai: "Khyber Pakhtunkhwa",
  Alpuri: "Khyber Pakhtunkhwa",
  "Akora Khattak": "Khyber Pakhtunkhwa",
  Ayubia: "Khyber Pakhtunkhwa",
  "Banda Daud Shah": "Khyber Pakhtunkhwa",
  Bannu: "Khyber Pakhtunkhwa",
  Shangla: "Khyber Pakhtunkhwa",
  Batkhela: "Khyber Pakhtunkhwa",
  Battagram: "Khyber Pakhtunkhwa",
  Birote: "Khyber Pakhtunkhwa",
  Bisham: "Khyber Pakhtunkhwa",
  Chakesar: "Khyber Pakhtunkhwa",
  Buner: "Khyber Pakhtunkhwa",
  Martung: "Khyber Pakhtunkhwa",
  Chakdara: "Khyber Pakhtunkhwa",
  Kana: "Khyber Pakhtunkhwa",
  Karora: "Khyber Pakhtunkhwa",
  Lilonai: "Khyber Pakhtunkhwa",
  Charsadda: "Khyber Pakhtunkhwa",
  Chitral: "Khyber Pakhtunkhwa",
  Maira: "Khyber Pakhtunkhwa",
  Shahpur: "Khyber Pakhtunkhwa",
  Daggar: "Khyber Pakhtunkhwa",
  Damorai: "Khyber Pakhtunkhwa",
  Dargai: "Khyber Pakhtunkhwa",
  Pirabad: "Khyber Pakhtunkhwa",
  "Kuz Kana": "Khyber Pakhtunkhwa",
  "Dera Ismail Khan": "Khyber Pakhtunkhwa",
  Doaba: "Khyber Pakhtunkhwa",
  Dir: "Khyber Pakhtunkhwa",
  Drosh: "Khyber Pakhtunkhwa",
  Hangu: "Khyber Pakhtunkhwa",
  Haripur: "Khyber Pakhtunkhwa",
  Karak: "Khyber Pakhtunkhwa",
  Kohat: "Khyber Pakhtunkhwa",
  Kulachi: "Khyber Pakhtunkhwa",
  Dandai: "Khyber Pakhtunkhwa",
  Shang: "Khyber Pakhtunkhwa",
  Ajmair: "Khyber Pakhtunkhwa",
  "Bela Baba": "Khyber Pakhtunkhwa",
  "Bar Puran": "Khyber Pakhtunkhwa",
  "Lakki Marwat": "Khyber Pakhtunkhwa",
  Latamber: "Khyber Pakhtunkhwa",
  Lelonai: "Khyber Pakhtunkhwa",
  Kotkay: "Khyber Pakhtunkhwa",
  Madyan: "Khyber Pakhtunkhwa",
  Mansehra: "Khyber Pakhtunkhwa",
  Mardan: "Khyber Pakhtunkhwa",
  Mastuj: "Khyber Pakhtunkhwa",
  Mingora: "Khyber Pakhtunkhwa",
  Nowshera: "Khyber Pakhtunkhwa",
  Paharpur: "Khyber Pakhtunkhwa",
  Pabbi: "Khyber Pakhtunkhwa",
  Peshawar: "Khyber Pakhtunkhwa",
  "Saidu Sharif": "Khyber Pakhtunkhwa",
  Shorkot: "Khyber Pakhtunkhwa",
  "Shewa Adda": "Khyber Pakhtunkhwa",
  Swabi: "Khyber Pakhtunkhwa",
  Swat: "Khyber Pakhtunkhwa",
  Tangi: "Khyber Pakhtunkhwa",
  Tank: "Khyber Pakhtunkhwa",
  Thall: "Khyber Pakhtunkhwa",
  Timergara: "Khyber Pakhtunkhwa",
  Tordher: "Khyber Pakhtunkhwa",

  // Balochistan Cities
  Awaran: "Balochistan",
  Barkhan: "Balochistan",
  Chagai: "Balochistan",
  "Dera Bugti": "Balochistan",
  Gwadar: "Balochistan",
  Harnai: "Balochistan",
  Jafarabad: "Balochistan",
  "Jhal Magsi": "Balochistan",
  Kacchi: "Balochistan",
  Kalat: "Balochistan",
  Kech: "Balochistan",
  Kharan: "Balochistan",
  Khuzdar: "Balochistan",
  "Killa Abdullah": "Balochistan",
  "Killa Saifullah": "Balochistan",
  Kohlu: "Balochistan",
  Lasbela: "Balochistan",
  Lehri: "Balochistan",
  Loralai: "Balochistan",
  Mastung: "Balochistan",
  Musakhel: "Balochistan",
  Nasirabad: "Balochistan",
  Nushki: "Balochistan",
  Panjgur: "Balochistan",
  "Pishin Valley": "Balochistan",
  Quetta: "Balochistan",
  Sherani: "Balochistan",
  Sibi: "Balochistan",
  Sohbatpur: "Balochistan",
  Washuk: "Balochistan",
  Zhob: "Balochistan",
  Ziarat: "Balochistan",

  Danyor: "Gilgit Baltistan",
};

// List of all cities derived from the mapping
export const CITIES = Object.keys(CITY_TO_PROVINCE);

export interface TrainingCenter {
  city: string;
  short: string;
}

export const TRAINING_CENTER: TrainingCenter[] = [
  { city: "Islamabad", short: "ISB" },
  { city: "Peshawar", short: "PEW" },
  { city: "Quetta", short: "QTA" },
  { city: "Karachi", short: "KHI" },
  { city: "Hyderabad", short: "HYD" },
  { city: "Sukkur", short: "SKR" },
  { city: "Rahim Yar Khan", short: "RYK" },
  { city: "Bahawalpur", short: "BWP" },
  { city: "Multan", short: "MUL" },
  { city: "Lahore", short: "LHE" },
  { city: "Faisalabad", short: "FSD" },
  { city: "Gujrat", short: "GUJ" },
  { city: "Jhelum", short: "JHE" },
  { city: "Sargodha", short: "SGD" },
];

export interface Bank {
  value: string;
  label: string;
  shortcut: string;
  matchcase: string;
  mobile?: boolean;
}

export const BANKS: Bank[] = [
  // DIGITAL PAYMENT METHODS
  {
    matchcase: "Mobilink Bank/JazzCash",
    value: "jazzcash",
    label: "Jazzcash",
    shortcut: "JCS",
    mobile: true,
  },
  {
    matchcase: "Telenor Microfinance Bank",
    value: "easypaisa",
    label: "Easypaisa",
    shortcut: "ETP",
    mobile: true,
  },
  {
    matchcase: "NayaPay",
    value: "nayapay",
    label: "NayaPay",
    shortcut: "NPY",
    mobile: true,
  },
  {
    matchcase: "SadaPay",
    value: "sadapay",
    label: "SadaPay",
    shortcut: "SDP",
    mobile: true,
  },
  {
    matchcase: "FINJA EMI",
    value: "finja",
    label: "Finja",
    shortcut: "FNJ",
    mobile: true,
  },
  {
    matchcase: "Keenu",
    value: "keenu",
    label: "Keenu",
    shortcut: "KNU",
    mobile: true,
  },

  // COMMERCIAL BANKS
  { matchcase: "ABL", value: "abl", label: "Allied Bank Ltd", shortcut: "ABL" },
  {
    matchcase: "Apna Bank",
    value: "apnabank",
    label: "Apna Bank",
    shortcut: "AMBL",
  },
  { matchcase: "Ubank", value: "ubank", label: "Ubank", shortcut: "UBK" },
  {
    matchcase: "National Savings",
    value: "nationalsavings",
    label: "National Savings",
    shortcut: "NSB",
  },
  {
    matchcase: "Samba",
    value: "sambabank",
    label: "Samba Bank Ltd",
    shortcut: "SMBL",
  },
  {
    matchcase: "Digitt",
    value: "Digittbank",
    label: "Digitt Bank",
    shortcut: "DGT",
  },
  {
    matchcase: "FINCA Microfinance",
    value: "finca",
    label: "FINCA Microfinance Bank",
    shortcut: "FMB",
  },
  {
    matchcase: "Askari Bank",
    value: "askari",
    label: "Askari Bank Ltd",
    shortcut: "ASK",
  },
  {
    matchcase: "Bank of Khyber",
    value: "bok",
    label: "The Bank of Khyber",
    shortcut: "BOK",
  },
  {
    matchcase: "Bank of Punjab",
    value: "bop",
    label: "The Bank of Punjab",
    shortcut: "BOP",
  },
  {
    matchcase: "Burj Bank",
    value: "burjbank",
    label: "Burj Bank Ltd",
    shortcut: "BRJ",
  },
  {
    matchcase: "Citi Bank",
    value: "citibank",
    label: "Citibank N.A.",
    shortcut: "CIT",
  },
  {
    matchcase: "Faysal Bank",
    value: "faysal",
    label: "Faysal Bank Ltd",
    shortcut: "FBL",
  },
  {
    matchcase: "HBL/KONNECT",
    value: "hbl",
    label: "Habib Bank Ltd",
    shortcut: "HBL",
  },
  {
    matchcase: "ICBC",
    value: "icbc",
    label: "Industrial and Commercial Bank of China",
    shortcut: "ICBC",
  },
  {
    matchcase: "Habib Metro",
    value: "habibmetro",
    label: "Habib Metropolitan Bank Ltd",
    shortcut: "HMB",
  },
  {
    matchcase: "Khushhali Bank",
    value: "khushhali",
    label: "Khushhali Microfinance Bank Ltd",
    shortcut: "KMBL",
  },
  { matchcase: "JS Bank", value: "js", label: "JS Bank Ltd", shortcut: "JSB" },
  { matchcase: "MCB", value: "mcb", label: "MCB Bank Ltd", shortcut: "MCB" },
  {
    matchcase: "NBP",
    value: "nbp",
    label: "National Bank of Pakistan",
    shortcut: "NBP",
  },
  {
    matchcase: "NBP Funds",
    value: "nbpfunds",
    label: "National Bank of Pakistan Funds",
    shortcut: "NBPF",
  },
  {
    matchcase: "NRSP Bank",
    value: "nrsp",
    label: "NRSP Bank Ltd",
    shortcut: "NRSP",
  },
  {
    matchcase: "Sindh Bank",
    value: "sindh",
    label: "Sindh Bank Ltd",
    shortcut: "SIBL",
  },
  {
    matchcase: "Silk Bank",
    value: "silkbank",
    label: "Silkbank Ltd",
    shortcut: "SILB",
  },
  {
    matchcase: "Soneri",
    value: "soneri",
    label: "Soneri Bank Ltd",
    shortcut: "SNBL",
  },
  {
    matchcase: "Standard Chartered",
    value: "scb",
    label: "Standard Chartered Bank Ltd",
    shortcut: "SCB",
  },
  {
    matchcase: "Summit Bank",
    value: "summit",
    label: "Summit Bank Ltd",
    shortcut: "SBL",
  },
  { matchcase: "UBL", value: "ubl", label: "United Bank Ltd", shortcut: "UBL" },
  {
    matchcase: "ZTBL",
    value: "ztbl",
    label: "Zarai Taraqiati Bank Ltd.",
    shortcut: "ZTB",
  },

  // ISLAMIC BANKS
  {
    matchcase: "Al Baraka",
    value: "albaraka",
    label: "AlBaraka Bank Ltd",
    shortcut: "ABB",
  },
  {
    matchcase: "Bank AlHabib",
    value: "alhabib",
    label: "Bank AL Habib Ltd",
    shortcut: "BAH",
  },
  {
    matchcase: "Bank Alfalah",
    value: "alfalah",
    label: "Bank Alfalah Ltd",
    shortcut: "BAF",
  },
  {
    matchcase: "Bank Islami",
    value: "bankislami",
    label: "BankIslami Pakistan Ltd",
    shortcut: "BIP",
  },
  {
    matchcase: "Dubai Islamic",
    value: "dubaiislamic",
    label: "Dubai Islamic Bank Pakistan Ltd",
    shortcut: "DIB",
  },
  {
    matchcase: "Meezan Bank",
    value: "meezan",
    label: "Meezan Bank Ltd",
    shortcut: "MBL",
  },
  {
    matchcase: "MCB Islamic",
    value: "mcbislamic",
    label: "MCB Islamic Bank",
    shortcut: "MCBI",
  },
  {
    matchcase: "MCB ARIF HABIB",
    value: "mcbarifhabib",
    label: "MCB Arif Habib Bank Ltd",
    shortcut: "MCBAH",
  },
];
